name: CI
on:
  pull_request:
    branches:
      - develop
jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [android]
        node: [16]
    env:
      NODE_ENV: "development"
    name: Testnpm run test
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Setup Node 🏗
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: install dependency
        run: npm install

      - name: run product
        run: npm run start
